# Generated by Django 5.1.2 on 2024-10-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skills/images'),
        ),
    ]
