# Generated by Django 5.1.2 on 2024-10-19 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0002_group_remove_user_ismaster_user_salary_user_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('work_period', models.CharField(max_length=100)),
                ('weekend', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('grade', models.IntegerField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekend',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_period',
        ),
    ]
