# Generated by Django 5.1.2 on 2024-10-31 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0003_portfolioimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_tel', models.CharField(max_length=100)),
                ('client_adders', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Ожидает выполнения'), ('in_progress', 'Выполняется'), ('completed', 'Выполнено')], default='pending', max_length=20)),
                ('master_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handyman.skills')),
            ],
        ),
    ]
