# Generated by Django 5.1.2 on 2024-11-05 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='banners/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['cat_name']},
        ),
        migrations.AlterField(
            model_name='service',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handyman.skills'),
        ),
    ]
